### ISSUE TITLE
Login fails silently with a trailing slash in the web address field

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/Pacific-SIS-App#1]
Perhaps do a strip trailing slash of this field to avoid this minor confusion.

![Screenshot_20230308-110158_Pacific-SIS](https://user-images.githubusercontent.com/1091769/223611939-02087fc9-6301-4e97-af8b-d70faca6f17f.jpg)

**Comment by sahaarpan5** [comment]
Done

**Comment by sahaarpan5** [comment]
Issue solved
