### ISSUE TITLE
Attendance timesout after taking one single successful attendance

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/Pacific-SIS-App#10]
The first attendance worked. But after a crash or browsing away from the attendance screen and returning is now simply spins for a long time and just fails to work and return to a prior screen.

![Screenshot_20230308_133541_Pacific-SIS](https://user-images.githubusercontent.com/1091769/223631018-1b427f49-bf3a-4857-ab3d-394b1582e36a.jpg)

**Comment by sahaarpan5** [comment]
done

**Comment by ghachey** [comment]
I have not seen the problem again since the last upgrade.
