### ISSUE TITLE
Dynamic logo like with web app

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/Pacific-SIS-App#11]
Can the app not get the logo dynamically from the catalogdb like the web app does nicely?

![Screenshot_20230308_134645_Pacific-SIS-logo](https://user-images.githubusercontent.com/1091769/223631405-18c199bb-5304-4495-8c11-d965c610d49b.jpg)

![logo-1](https://user-images.githubusercontent.com/1091769/223631444-e3faf24c-c92f-455d-9fe0-3189e3f40b49.png)

**Comment by sahaarpan5** [comment]
done

**Comment by ghachey** [comment]
Does not seem to work in the latest in the playstore. At least not when trying with the online https://pacificsis.pacific-emis.org/. See when login in online.

![pacific-sis-app-logo-2](https://user-images.githubusercontent.com/1091769/227867644-a6713ad0-9410-4efa-a0a0-a8e293adaaf4.jpg)

And 
![pacific-sis-app-logo-1](https://user-images.githubusercontent.com/1091769/227867656-ffa81bca-503e-4363-8aff-71ad56beba51.jpg)

when login in the app.

![pacific-sis-app-logo-3](https://user-images.githubusercontent.com/1091769/227867814-d26dd816-07e2-4d66-a927-be4a978a26cf.jpg)

I have not uninstalled and re-install the app. This was merely the automatic upgrade of the app.

I did try to clear the Pacific SIS app cache to no avail.

**Comment by ghachey** [comment]
Discard previous comment. This only required a logout and login again of the app and now works great.
