### ISSUE TITLE
Replace Pacific EMIS with Pacific SIS

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/Pacific-SIS-App#13]
A sister logo of the Pacific EMIS called the Pacific SIS was provided (also a white version as shown below). Can the Pacific EMIS logo be replaced with the Pacific SIS logo. Also please replace all references to Pacific EMIS with Pacific SIS where underlined in red.

![pacific-sis-app-logo-4](https://user-images.githubusercontent.com/1091769/227869607-7ba6d079-5330-4ae5-b9e0-239363065021.jpg)

**Comment by openSISAdmin** [comment]
Update the logo and the text as highlighted. Make them all PacificSIS.

**Comment by ghachey** [comment]
Even better if the default Pacific SIS logo and strings get dynamically updated with the catalogdb values (MISIS, FedSIS, etc.) of the logged in country. Just like the behavior of the web app.

**Comment by ghachey** [comment]
Great stuff!
