### ISSUE TITLE
Minor correction in attendance UI

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/Pacific-SIS-App#14]
In the web app for non school days the user can not choose the date. Which I would say is an appropriate behavior.

![pacific-sis-attendance-2](https://user-images.githubusercontent.com/1091769/227871937-814c0e97-a063-4975-8be3-2c841094c0c6.jpg)

However, in the app there is no such constraint. As a result, the user can be faced with a slightly inconsistent screen as shown below (i.e. it shows attendance taken for a non-school day which is however correctly identified as "No record" though). 

![pacific-sis-attendance-1](https://user-images.githubusercontent.com/1091769/227872157-ee4d5bd7-a99d-4c40-8da4-1f0f95d1c32f.jpg)

**Comment by openSISAdmin** [comment]
This is a bug

**Comment by ghachey** [comment]
Seems fixed. It does still allow the selection of non-school days but at least returns valid feedback which is acceptable.
