### ISSUE TITLE
Student profile picture not showing

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/Pacific-SIS-App#15]
Web app.

![student-pic-1](https://user-images.githubusercontent.com/1091769/227874647-8ede0426-ee96-4969-9bc6-37fc4f92c732.jpg)

Mobile app.

![student-pic-2](https://user-images.githubusercontent.com/1091769/227874675-ad8ca372-5713-4925-8776-2b1cc7b1618d.jpg)

**Comment by ghachey** [comment]
This is actually working. Not sure why it took a while but loading correctly now...

**Comment by ghachey** [comment]
I now know why I did not see it working the first time. It seems there is a slightly inconsistent behavior. When the attendance has not been taken, the student profile picture is showing correctly.

![student-pic-2](https://user-images.githubusercontent.com/1091769/227881361-98db3acd-9819-443b-af0c-252b39377f8f.jpg)

As soon as the attendance is taken the student profile picture returns to the default icon.

![student-pic-3](https://user-images.githubusercontent.com/1091769/227881505-1efd665d-326a-488e-a951-0bab0b8dde73.jpg)

**Comment by ghachey** [comment]
@sahaarpan5 and @openSISAdmin this is working under attendance tab. However, it is still not showing under the Student tab where arguably it should be in the first place. Check attendance tab below is working.

![Screenshot 2023-04-18 144102](https://user-images.githubusercontent.com/1091769/232692964-e249db54-085c-4335-80ff-a01d2bc61602.jpg)

But not under Student tab.

![Screenshot 2023-04-18 144150](https://user-images.githubusercontent.com/1091769/232693016-a9efbfe2-5d1b-45e2-ad0a-0b00a4e1fb1a.jpg)

**Comment by ghachey** [comment]
@openSISAdmin I do not see this in the latest build, no.

**Comment by sahaarpan5** [comment]
@ghachey new APK has been live in play store.Please check now.

**Comment by ghachey** [comment]
Working now
