### ISSUE TITLE
Cache latest entered and correctly logged in web address

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/Pacific-SIS-App#16]
This is a very minor enhancement. But many users might needs to get support for simple things as remembering the web address which they don't often use. Upon successful login to a web address (i.e. a SIS) it would be useful this would be cached and simply selectable from a dropdown list instead of typing everytime.

![web-address-caching](https://user-images.githubusercontent.com/1091769/227877097-9dec36c5-2597-497d-af53-515a2a9a5bf9.jpg)

**Comment by openSISAdmin** [comment]
@sahaarpan5 

I think you should have a remember me checkbox like the web app. We do not want users to enter URL, username, and password every time they want to get into the SIS. They should get logged in automatically.

**Comment by ghachey** [comment]
Fixed
