### ISSUE TITLE
Make welcome page more like the web app

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/Pacific-SIS-App#17]
Can we make the welcome page more like the familiar and beautiful web app welcome page? On the left is the app welcome page and the ocean pic does not really match well the blue of the logged in app. On the right is a version more inspired by the web app which is very sleek. Can the mobile app be more like that (on the right)?

![welcome-screen](https://user-images.githubusercontent.com/1091769/227891654-20cc5d3a-c874-4adb-bede-b683af32da7b.jpg)

**Comment by sahaarpan5** [comment]
Done

**Comment by ghachey** [comment]
@sahaarpan5 is this already published in the playstore? I do not see the change.

**Comment by ghachey** [comment]
Fixed
