### ISSUE TITLE
Missing courses for teachers

### ISSUE THREAD

**Issue by nlangidrik** [PacificEMIS/Pacific-SIS-App#18]
Upon logging in with a teacher account, teacher's courses for the day do not appear on the app even though the teacher does have courses. 

![image](https://user-images.githubusercontent.com/125524626/228426839-6a42478a-c1ab-4c34-8a5e-9037b263fc45.png)

![image](https://user-images.githubusercontent.com/125524626/228426885-c8da8772-9b43-422e-8ada-42f86514a885.png)

This is the view of the scheduled courses for the teacher.

![image](https://user-images.githubusercontent.com/125524626/228427070-757507f1-fb87-4824-8a8a-2ee6018467e5.png)

**Comment by ghachey** [comment]
Seems fixed
