### ISSUE TITLE
Remove the hard coded unknown person as the profile of logged in teacher

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/Pacific-SIS-App#2]
Even changing the profile photo in the web app does not change this hard coded photo of unknown person.

![Screenshot_20230308-114515_Pacific-SIS](https://user-images.githubusercontent.com/1091769/223612057-1b051181-4a86-4dd8-bd5d-bff54fb37fce.jpg)

**Comment by sahaarpan5** [comment]
Issue solved
