### ISSUE TITLE
Missing attendance notification does not update

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/Pacific-SIS-App#25]
Minor issue. When opening the app the teacher sees the missing attendance. Then we take attendance. Upon return to the dashboard page the missing attendance notification is not updated. One needs to browse away of the dashboard and come back which is not as streamlined.

![Screenshot 2023-04-20 143648](https://user-images.githubusercontent.com/1091769/233281589-dc1d69b6-17b4-4ea4-ba00-5bd29e036038.jpg)

**Comment by sahaarpan5** [comment]
@ghachey please check..New update is available in play store

**Comment by ghachey** [comment]
Confirmed working
