### ISSUE TITLE
Taking attendance times out and return to login screen

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/Pacific-SIS-App#28]
Blocking issue making the app still unusable for all practical purposes.  Core feature of taking attendance simply times out and returns to login screen.

To reproduce, use the online demo system at https://pacificsis.pacific-emis.org/

Use same credentials as provided to @openSISAdmin by email and checkout the course section "Homeroom Attendance - Grade 2 - Section A - Homeroom"

**Comment by sahaarpan5** [comment]
@ghachey sir Can you please update the application and check again.Issue solved from my end

**Comment by ghachey** [comment]
@sahaarpan5 Yes, it did seem to work when I tried again. We'll consider this resolved. Please merge all the source code into the relevant Branch.
