### ISSUE TITLE
Takes attendance in course section with no attendance to be taken

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/Pacific-SIS-App#3]
Check below. This course is a course section with no attendance to be taken (it is only in Homeroom attendance for this school).

![Screenshot_20230308-114554_Pacific-SIS](https://user-images.githubusercontent.com/1091769/223614306-d9046b01-30e5-42a1-819e-f56e4f97b687.jpg)

See the configuration of period attendance below.

![attendance-config](https://user-images.githubusercontent.com/1091769/223614550-646f550e-d71f-4eaa-94cc-50183d9a0282.png)

And also of the course where the tablet allows to take attendance.

![attendance-config-2](https://user-images.githubusercontent.com/1091769/223614755-95fabf2b-0433-4b65-9f41-cb3e7232d872.png)

I would expect something more like the web app as shown below from logged in Teacher.

![attendance-config-3](https://user-images.githubusercontent.com/1091769/223615020-afcc9a8c-41e5-44bf-bbc6-a9314acfef20.png)

**Comment by sahaarpan5** [comment]
Issue solved
