### ISSUE TITLE
Hard coded unknown person profile for all students in the tablet

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/Pacific-SIS-App#4]
Should default to a user icon when not available and when student profile photo is available should download that one asynchronously and cache it in the tablet for future use.

![Screenshot_20230308-114554_Pacific-SIS](https://user-images.githubusercontent.com/1091769/223615290-cfa98645-9eeb-4076-9f2a-4411b9bdcb32.jpg)

**Comment by sahaarpan5** [comment]
Issue solved
