### ISSUE TITLE
Attendance options all in green

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/Pacific-SIS-App#5]
Can the colors not be like the web app making it a little bit more clear?

![Screenshot_20230308-114617_Pacific-SIS](https://user-images.githubusercontent.com/1091769/223615506-5c5fa751-4bbb-4be7-a553-6f077f621804.jpg)

vs the web app.

![attendance-colors](https://user-images.githubusercontent.com/1091769/223615617-e4da6d01-9c31-4124-a247-4b0ff820bdce.png)

**Comment by sahaarpan5** [comment]
Done
