### ISSUE TITLE
Constant crashing

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/Pacific-SIS-App#7]
The app is very unstable. We experience constant crashing. Hard to repeat, it just crashes any time with no distinct patterns. To see just login using the test site https://pacificsis.pacific-emis.org (I can send teacher credentials by email)

![Screenshot_20230308-114923_Pacific-SIS](https://user-images.githubusercontent.com/1091769/223616676-3a2c83ca-b802-4165-9bff-380927b2813b.jpg)

![Screenshot_20230308-114947_Pacific-SIS](https://user-images.githubusercontent.com/1091769/223616688-79704c06-1c09-4ba5-b754-b673b24b4a3f.jpg)

**Comment by sahaarpan5** [comment]
done

**Comment by ghachey** [comment]
This so far testing all latest updates as been working beautifully!
